[package]
name = "rdkit-rust-ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0"


[build-dependencies]
cxx-build = "1.0"
dotenvy = "0.15.7"
walkdir = "2.5.0"
env_logger = "0.11.5"
which = "6.0.3"
